### PR TITLE
Adapted to linux, renamed executable to sarcasm

### PR DESCRIPTION
**Pull request by handicraftsman**

### CODE REVIEW

**Comment by handicraftsman** [comment]
Should run on macOS too.

**Comment by telephil** [comment]
Hi,
Thanks for the PR, did not know I had such a huge user base :)
I was planning to get to this, but with a slightly different approach that I feel would be cleaner. I'll push my change tonight.

One question though, why do you need the call to patchelf ?

Thanks

**Comment by handicraftsman** [comment]
patchelf is called only on linux and is used to set rpath (runtime library loading path) to the same directory as the executable. This allows calling the binary without installing it. Still need to add .scm loading support in code for the current directory.

**Comment by handicraftsman** [comment]
As for concurrency implementation (srfi 18), you could check https://github.com/sustrik/libdill

I don't know if it works on macOS though - don't have a mac.

**Comment by handicraftsman** [comment]
Closing the PR because its content is reimplemented in a cleaner way.

**Comment by telephil** [comment]
Thanks a lot for your help Nickolay.
I'll need to add the patchelf call or first compile a static lib for the
interpreter and a dynamic library for other libraries (I think this is the
standard way to proceed).

I'll look into libdill thanks for the pointer.

**Pull request closed without merging**
